/*Sample call  :http://localhost:3000/api/user?operator=GREATERTHAN&value=70&age=desc&size=20
Method: GET

Output:{"userList":[{"id":461,"first_name":"Glen","last_name":"Lipp","email":"glippcs@buzzfeed.com","gender":"Female","age":72},{"id":431,"first_name":"Viva","last_name":"Linne","email":"vlinneby@issuu.com","gender":"Female","age":72},{"id":280,"first_name":"Berkeley","last_name":"Anderl","email":"banderl7r@tiny.cc","gender":"Male","age":72},{"id":188,"first_name":"Bertie","last_name":"Pittendreigh","email":"bpittendreigh57@wikimedia.org","gender":"Male","age":72},{"id":140,"first_name":"Avril","last_name":"Casin","email":"acasin3v@ted.com","gender":"Female","age":72},{"id":139,"first_name":"Merrielle","last_name":"Ravilious","email":"mravilious3u@un.org","gender":"Female","age":72},{"id":107,"first_name":"Egon","last_name":"Ardron","email":"eardron2y@hostgator.com","gender":"Male","age":72},{"id":37,"first_name":"Bobbie","last_name":"MacAless","email":"bmacaless10@hao123.com","gender":"Female","age":72},{"id":950,"first_name":"Court","last_name":"Defau","email":"cdefauqd@webnode.com","gender":"Male","age":71},{"id":850,"first_name":"Hilde","last_name":"Corley","email":"hcorleynl@telegraph.co.uk","gender":"Female","age":71},{"id":805,"first_name":"Hilda","last_name":"Standidge","email":"hstandidgemc@samsung.com","gender":"Female","age":71},{"id":526,"first_name":"Alphard","last_name":"Maycock","email":"amaycockel@yellowpages.com","gender":"Male","age":71},{"id":353,"first_name":"Ronnie","last_name":"Topham","email":"rtopham9s@artisteer.com","gender":"Male","age":71},{"id":304,"first_name":"Shandeigh","last_name":"Ivers","email":"sivers8f@google.fr","gender":"Female","age":71},{"id":237,"first_name":"Annmaria","last_name":"Enders","email":"aenders6k@google.nl","gender":"Female","age":71},{"id":187,"first_name":"Sutherlan","last_name":"Freegard","email":"sfreegard56@usatoday.com","gender":"Male","age":71},{"id":89,"first_name":"Willa","last_name":"Millea","email":"wmillea2g@goo.gl","gender":"Female","age":71},{"id":85,"first_name":"Ravid","last_name":"Coronado","email":"rcoronado2c@sun.com","gender":"Male","age":71},{"id":64,"first_name":"Trudy","last_name":"De Blasiis","email":"tdeblasiis1r@salon.com","gender":"Female","age":71},{"id":10,"first_name":"Arch","last_name":"Redmille","email":"aredmille9@msn.com","gender":"Male","age":71}]}*/

/* Sample call :http://localhost:3000/api/user?operator=LESSTHAN&value=70&age=asc&size=10
 Method:GET
Output:{"userList":[{"id":110,"first_name":"Amelia","last_name":"Genn","email":"agenn31@indiegogo.com","gender":"Female","age":69},{"id":321,"first_name":"Derby","last_name":"Webberley","email":"dwebberley8w@naver.com","gender":"Male","age":69},{"id":446,"first_name":"Betteanne","last_name":"Clough","email":"bcloughcd@businesswire.com","gender":"Female","age":69},{"id":498,"first_name":"Joe","last_name":"Heggman","email":"jheggmandt@soup.io","gender":"Male","age":69},{"id":539,"first_name":"Micheil","last_name":"Betteridge","email":"mbetteridgeey@hostgator.com","gender":"Male","age":69},{"id":595,"first_name":"Padriac","last_name":"McVie","email":"pmcviegi@soundcloud.com","gender":"Male","age":69},{"id":621,"first_name":"Trumaine","last_name":"Tucsell","email":"ttucsellh8@cisco.com","gender":"Male","age":69},{"id":678,"first_name":"Forster","last_name":"Dowty","email":"fdowtyit@wordpress.com","gender":"Male","age":69},{"id":820,"first_name":"Rudolfo","last_name":"Gudge","email":"rgudgemr@smugmug.com","gender":"Male","age":69},{"id":848,"first_name":"Chelsie","last_name":"Bearne","email":"cbearnenj@huffingtonpost.com","gender":"Female","age":69}]}*/

//For starting the code base: node app.js

/*Description: At first ,call hits app.js then routes/index.js .
 index.js is the routing file .
In user.js, contains the user validation function for filter,sort,pagination. At first the data is read
using fs.readFile then the data is filtered using age , operator(query data) and value. This filtered 
data is stored in userFilterDataList array .Then new array(userFilterDataList) will be sorted using
lodash.sortby module , age (query data) and stored in userSortDataList array. Then userSortDataList 
array will be paginated by paginator function(../pagination/generator.js) . Result will be wriiten in
output.json file using fs.writeFile .*/
